import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import './globals.css';
import { Toaster } from '@/components/ui/sonner';

import { ClerkProvider } from '@clerk/nextjs';

import ConvexClientProvider from '@/components/providers/ConvexClientProvider';
import Navbar from '@/components/Navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Pro-Learner',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} relative h-full antialiased`}
    >
      <body className='min-h-full flex flex-col'>
        <ClerkProvider>
          <ConvexClientProvider>
            <div className='absolute inset-0 -z-10 h-full w-full bg-white bg-[linear-gradient(to_right,#f0f0f0_1px,transparent_1px),linear-gradient(to_bottom,#f0f0f0_1px,transparent_1px)] bg-size-[6rem_4rem]'>
              <div className='absolute bottom-0 left-0 right-0 top-0 bg-[radial-gradient(circle_800px_at_100%_200px,#d5c5ff,transparent)]'></div>
            </div>
            <Navbar />

            {children}
            <Toaster position='top-center' />
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
